export enum MessageType {
  MESSAGE_EVENT = 'MESSAGE_EVENT',
  QUEUE = 'QUEUE',
  MPD_OFFLINE = 'MPD_OFFLINE',
  REQUEST_STATUS = 'REQUEST_STATUS',
  STATUS = 'STATUS',
  PLAY = 'PLAY',
  PAUSE = 'PAUSE',
  RANDOM = 'RANDOM',
};