export enum MPDStatus {
  DISCONNECTED = 1,
  CONNECTION = 2,
  RECONNECTION = 3,
  READY = 4,
}

export enum PlayStatus {
  UNKONWN = 'unkonwn',
  PLAY = 'play',
  STOP = 'stop',
  PAUSE = 'pause',
}

export enum MessageType {
  MPD_ERROR = 'MPD_ERROR',

  MESSAGE_EVENT = 'MESSAGE_EVENT',

  STATUS = 'STATUS',
  REQUEST_STATUS = 'REQUEST_STATUS',

  QUEUE = 'QUEUE',
  REQUEST_QUEUE = 'REQUEST_QUEUE',

  LIBRARY = 'LIBRARY',
  REQUEST_LIBRARY = 'REQUEST_LIBRARY',

  CLEAR_QUEUE = 'CLEAR_QUEUE',
  REQUEST_CLEAR_QUEUE = 'REQUEST_CLEAR_QUEUE',

  MPD_STATUS = 'MPD_STATUS',
  REQUEST_MPD_STATUS = 'REQUEST_MPD_STATUS',

  REQUEST_ADD_TO_QUEUE = 'REQUEST_ADD_TO_QUEUE',

  OPERATION_SUCCESS = 'OPERATION_SUCCESS',

  REQUEST_PLAY = 'REQUEST_PLAY',
  REQUEST_DELETE = 'REQUEST_DELETE',
  REQUEST_NEXT = 'REQUEST_NEXT',
  REQUEST_PREVIOUS = 'REQUEST_PREVIOUS',
  REQUEST_PAUSE = 'REQUEST_PAUSE',
  REQUEST_RANDOM = 'REQUEST_RANDOM',
  REQUEST_REPEAT = 'REQUEST_REPEAT',
  REQUEST_SINGLE = 'REQUEST_SINGLE',
  REQUEST_SET_VOL = 'REQUEST_SET_VOL',
};