import type { Metadata } from 'next';

import { Provider } from './provider';
import { status } from './api/status/route';

import './globals.css';

export const metadata: Metadata = {
  title: 'MPD Client Player by Nextjs',
  description: 'Generated by Nextjs',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let data = null;
  try {
    const response = await status();
    data = response.data;
  } catch {
    // do nothing
  }
  return (
    <html lang="en">
      <body className="p-4 flex flex-col h-screen max-w-lg m-auto">
        <Provider value={data || null}>{children}</Provider>
      </body>
    </html>
  );
}
