import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'MPD Player by Nextjs',
  description: 'Generated by Nextjs',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="p-4 flex flex-col h-screen">{children}</body>
    </html>
  );
}
